import './globals.css';
import styles from './layout.module.css';
import Nav from '@/components/Nav/Nav';
import Card from '@/components/Card/Card';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={styles.grid}>
				<aside className={styles.card}>
					<Card />
				</aside>
				<main className={styles.content}>{children}</main>
				<nav className={styles.nav}>
					<Nav />
				</nav>
			</body>
		</html>
	);
}
